#!/bin/bash

echo "Running ORF executable"
cd $/home/16.831/ORF/
./ORF &
ORF_PID = $!
echo ORF_PID

echo "Running ThermoCam executable"
cd $/root/thermorf/thermorf/
source /opt/pleora/ebus_sdk/RHEL-6-i686/bin/set_puregev_env
./thermorf &
thermocam_PID = $!
echo thermocam_PID

echo "Running Goggles executable"
cd $/home/GPF_DIR/build/bin/
./TP_1106_Capture /home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt &
goggles_PID = $!
echo goggles_PID

sleep 10m

kill -SIGKILL ORF_PID & kill -SIGKILL thermocam_PID & kill -SIGKILL goggles_PID

##################################################################

# echo "Running ORF executable"
# (cd $/home/16.831/ORF/; ./ORF)
# echo "Running ThermoCam executable"
# (cd $/root/thermorf/thermorf/; source /opt/pleora/ebus_sdk/RHEL-6-i686/bin/set_puregev_env; ./thermorf)
# echo "Running Goggles executable"
# (cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture /home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt)


################################################################


# echo "Running ORF, ThermoCam, and Goggles executables"
# orfcmd = "cd $/home/16.831/ORF/; ./ORF"
# thermocmd = "cd $/root/thermorf/thermorf/; source /opt/pleora/ebus_sdk/RHEL-6-i686/bin/set_puregev_env; ./thermorf"
# gogglescmd = "cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture /home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt"

# gnome-terminal \
#   --tab-with-profile=Default -e $orfcmd \
#   --tab-with-profile=Default -e $thermocmd \
#   --tab-with-profile=Default -e $gogglescmd


###############################################################


# tab="--tab-with-profile=Default -e "
# orfcmd="cd $/home/16.831/ORF/; ./ORF"
# echo "Running ORF executable"
# gnome-terminal --tab -e $orfcmd
# thermocmd="cd $/root/thermorf/thermorf/; source /opt/pleora/ebus_sdk/RHEL-6-i686/bin/set_puregev_env; ./thermorf"
# echo "Running ThermoCam executable"
# gnome-terminal --tab -e $thermocmd
# gogglescmd="cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture /home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt"
# echo "Running Goggles executable"
# gnome-terminal --tab -e $gogglescmd
