#!/bin/bash
# My first script

# echo "Running ORF executable"
# (cd $ORF/; ./ORF)
# echo "Running ThermoCam executable"
# (cd $ThermoCam/ThermoCamStream/; ./Thermo)
# echo "Running Goggles executable"
# (cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture/home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt)

tab="--tab-with-profile=Default -e "
cmd="cd $ORF/; ./ORF"
echo "Running ORF executable"
gnome-terminal --tab -e $cmd
tab="--tab-with-profile=Default -e "
cmd="cd $ThermoCam/ThermoCamStream/; ./Thermo"
echo "Running ThermoCam executable"
gnome-terminal --tab -e $cmd
tab="--tab-with-profile=Default -e "
cmd="cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture/home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt"
echo "Running Goggles executable"
gnome-terminal --tab -e $cmd
