#!/bin/bash

# echo "Running ORF executable"
# (cd $ORF/; ./ORF)
# echo "Running ThermoCam executable"
# (cd $ThermoCam/ThermoCamStream/; ./Thermo)
# echo "Running Goggles executable"
# (cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture/home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt)


################################################################


orfcmd = "cd $ORF/; ./ORF"
thermocmd = "cd $ThermoCam/ThermoCamStream/; ./Thermo"
gogglescmd = "cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture/home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt"

gnome-terminal \
  --tab-with-profile=Default -e $orfcmd \
  --tab-with-profile=Default -e $thermocmd \
  --tab-with-profile=Default -e $gogglescmd

echo "Running ORF, ThermoCam, and Goggles executables"


###############################################################


# tab="--tab-with-profile=Default -e "
# orfcmd="cd $ORF/; ./ORF"
# echo "Running ORF executable"
# gnome-terminal --tab -e $orfcmd
# thermocmd="cd $ThermoCam/ThermoCamStream/; ./Thermo"
# echo "Running ThermoCam executable"
# gnome-terminal --tab -e $thermocmd
# gogglescmd="cd $/home/GPF_DIR/build/bin/; ./TP_1106_Capture/home/GPF_DIR CURRENT_CALIB_DIR pFile-nosphere.txt"
# echo "Running Goggles executable"
# gnome-terminal --tab -e $gogglescmd
